# Generated by Django 4.2.1 on 2023-05-31 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("sku", models.IntegerField(primary_key=True, serialize=False)),
                ("precio", models.IntegerField()),
                ("nombre", models.CharField(max_length=50)),
                ("imagen", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=80)),
                ("stock", models.IntegerField()),
                ("fechaAgregar", models.DateField(auto_now_add=True)),
                (
                    "categoria_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Tienda.categoria",
                    ),
                ),
            ],
        ),
    ]
